### ISSUE TITLE
How to set code font into Monaco?

### ISSUE THREAD

**Issue by deweixu** [isagalaev/highlight.js#1057]
Monaco

**Comment by sourrust** [comment]
If your browser has the font, you can use CSS:

```css
.hljs {
  font-family: Monaco;
}
```
