### ISSUE TITLE
SCSS/CSS Highlighting doesn't work correctly with custom-elements

### ISSUE THREAD

**Issue by thibaultsavary** [isagalaev/highlight.js#1467]
Custom elements should be supported as it's slowly becoming the new norm.

Hyphen separated tag should be highlighted correctly. (see #1442)
First properties after certain selector aren't rendered correctly.
i.e.
```css
:host {
 display: block;
 display: block;
}
```
The first `display` property isn't rendered correctly, while the second one is.
