### ISSUE TITLE
CSS Pseudo-classes problem

### ISSUE THREAD

**Issue by temp-impl** [isagalaev/highlight.js#938]
CSS highlighting breaks on the following code.
```css
td:nth-child(-n+2) {
    background-color: purple;
}
```
http://jsfiddle.net/xnqteq7L/

I think there are some problem with colon parsing.
