### ISSUE TITLE
Haskell Source Code is failed

### ISSUE THREAD

**Issue by Tekkkz** [isagalaev/highlight.js#943]
Hello!
Why is my highlighting at: http://tekkkz.com/posts/articles/arch_installation.html Broken?

My code is:
    <link rel="stylesheet" href="../../css/styles/monokai.css">
    <script src="../../js/highlight.pack.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    
    <pre>
      <code class="haskell">
        {-# OPTIONS_GHC -Wall #-}
        euclid :: Int -> Int -> Int
        euclid a b
          | a == 0    = b
          | b == 0    = a
          | a > b     = euclid (a-b) b
          | otherwise = euclid a (b-a)
      </code>
    </pre>

Why is it broken?

**Comment by sourrust** [comment]
It looks like there is something in your css that is moving `span`s around:

```css
.content span {
  float: left;
  padding-right: 50px;
}
```

I remove it and the result is this:

![](https://cloud.githubusercontent.com/assets/365596/10117006/5598b4c0-63fc-11e5-90f3-556bdea85630.PNG)

Rather than removing it outright, you might want to add something like:

```css
.hljs span {
  float: none;
  padding: 0;
}
```
